package tddstart;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsEqual.equalTo;

public class DictionnaryTest {
    Dictionnary dict = new Dictionnary("test1");

    @Test
    public void testDictionaryName() {
        assertThat(dict.getName(), equalTo("test1"));
    }

    @Test
    public void testDictionaryIsEmpty() {
        assertThat(dict.isEmpty(), equalTo(true));
    }

    @Test public void testOneTranslation() {
        dict.addTranslation("contre", "against");
        assertThat(dict.getTranslation("contre"), equalTo("against"));
    }

    @Test public void testTwoTranslation() {
        dict.addTranslation("contre", "against");
        assertThat(dict.getTranslation("contre"), equalTo("against"));
    }
}
